### ISSUE TITLE
Work needed here to support instance initializers

### ISSUE THREAD

**Issue by jasonmit** [ember-cli/ember-load-initializers#13]
Just opening this here since the discussion started in ember-cli:
https://github.com/ember-cli/ember-cli/issues/3159

I'd be happy to take this on, even if it's a bit premature :)

**Comment by stefanpenner** [comment]
@jasonmit good catch.

**Comment by brzpegasus** [comment]
@jasonmit Have you started any work on this? I was thinking of taking a stab at it otherwise.

**Comment by stefanpenner** [comment]
@brzpegasus i don't think we have had a chance yet, so feel free to take the stab.
