### ISSUE TITLE
Deprecation Ember 2+

### ISSUE THREAD

**Issue by Blackening999** [ember-cli/ember-load-initializers#22]
DEPRECATION: Ember.keys is deprecated in favor of Object.keys [deprecation id: ember-metal.ember.keys]

Update please

**Comment by jcope2013** [comment]
you using 0.1.7 in your bower.json?

https://github.com/ember-cli/ember-load-initializers/commit/78470bed646d76e176c1bc405796b3aeb01940f5

**Comment by rwjblue** [comment]
The latest version does not issue deprecations.

**Comment by Blackening999** [comment]
Confirm that... I had 0.14 
sorry for the mess
