### ISSUE TITLE
Adding `__esModule: true` property

### ISSUE THREAD

**Issue by zoltan-nz** [ember-cli/ember-load-initializers#27]
Hi @stefanpenner , I'm just wondering, is it possible to add a `babel` compatible `__esModule` property to all Ember dependency, like this `ember-load-initializers` and `ember-resolver`?

I try to use these packages without ember-cli, in a "legacy", kind of Ember App Kit project. A first step would be to make it ES6 compatible with Babel, later I can move the whole project under ember-cli.

I was able to solve this problem to creating a custom shims, which is adding `__esModule` property to these packages... but I thought, maybe it would be useful for more people.

What do you think?

**Comment by stefanpenner** [comment]
if you choose babels option for `modules: "amdStrict" ` this will be compatible.

**Comment by zoltan-nz** [comment]
@stefanpenner Thanks for your suggestion. It looks, this module is not supported in Babel v6 any more, or I still missing something. :)

**Comment by zoltan-nz** [comment]
@stefanpenner I've just realized, Ember Twiddle had the same problem, so they just wrote a monkey patch. https://github.com/ember-cli/ember-twiddle/blob/master/app/services/ember-cli.js#L477 :)

**Comment by stefanpenner** [comment]
It's a Babel 6 plugin I believe

**Comment by zoltan-nz** [comment]
I havent found any. I checked the transformer's source code as well, and there is no option to turning off this _esModule injection.

Anyway, I realized you still use everywhere Babel v5, in broccoli-babel also. So I just use an earlier version of grunt-babel in my project, which works as you suggested.

**Comment by stefanpenner** [comment]
sounds good for now.
