### ISSUE TITLE
[v3] Could not find module `ember-load-initializers` imported from `(require)`

### ISSUE THREAD

**Issue by mkszepp** [ember-cli/ember-load-initializers#309]
Using inside my embroider app i'm getting error:
`Could not find module `ember-load-initializers` imported from `(require)`

Inside a new clean [repo](https://github.com/mkszepp/test-ember-load-initializers) (classic) we are getting an other error see https://github.com/mkszepp/test-ember-load-initializers/actions/runs/11046810011/job/30686819289#step:5:62

**Comment by mkszepp** [comment]
Error in classic:

`Module not found: Error: Invalid "exports" target "dist/index.js" defined for "." in the package config /tmp/broccoli-1851r09KjyAsYHsR/cache-150-webpack_bundler_ember_auto_import_webpack/node_modules/ember-load-initializers/package.json, targets must start with "./"`

**Comment by ef4** [comment]
Fixed in #308.
