### ISSUE TITLE
Could not find module `ember-local-storage/initializers/local-storage-adapter

### ISSUE THREAD

**Issue by betocantu93** [ember-cli/ember-load-initializers#311]
After upgrading to ember 5.x I started getting errors with initializers, I bumped to the latest ember-load-initializers version still no luck... any guess? or any debugging I can do?

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Update package.json to ensure compatibility with Ember 5.x and add debugging information to index.ts to help users troubleshoot initializer issues.

You can review changes in this commit: https://github.com/mnmnk43434/ember-cli-ember-load-initializers-311/commit/6d4cb1d9033fb1f385da2321aff6093ab6ac3b2d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by betocantu93** [comment]
It seems that ember localstorage migrated from using initializers. That was my fix.
