### ISSUE TITLE
Add repository information to package.json

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-load-initializers#32]
so that it shows on https://www.npmjs.com/package/ember-load-initializers and so that GreenKeeper is able to show more information

**Comment by rwjblue** [comment]
closed by https://github.com/ember-cli/ember-load-initializers/commit/5c81fc64e5d691bea41457a35f63de9348b5f7a9

**Comment by Turbo87** [comment]
@rwjblue did you see https://github.com/ember-cli/ember-load-initializers/pull/35?

**Comment by rwjblue** [comment]
Apparently not 😿
