### ISSUE TITLE
your releases page seems out of date

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-load-initializers#43]
says the latest version is v0.1.5

<img width="1070" alt="screenshot_4_11_17__5_11_pm" src="https://cloud.githubusercontent.com/assets/497659/24935900/df06a2be-1ed9-11e7-976d-c04d65548cb1.png">

**Comment by jeffrey008** [comment]
Yup this is really confusing for people, I just tricked by that. How could we tag 1.0 as latest release?

**Comment by rwjblue** [comment]
Well, I suppose we just need to update it. The issue here is that the github UI handles this pretty oddly.  I’ve addressed the immediate issue of GH not showing the latest tags by deleting the one release that was manually created. Now all are shown.

Sorry this caused folks trouble.
